---
title: "环境健康领域简介"
linkcolor: '#08519c'
navbar: right
---

环境流行病学是环境卫生学中的一门分支学科。是应用流行病学的原理与方法研究环境因素对人群健康状况影响的一门学科。

环境流行病学肇始于地球化学性疾病的研究 (如地方性甲状腺肿、地方性氟中毒等)。自从“污染物”成为重要的环境因素以来，陆续发现一些原因不明的疾病与环境中的污染物有关，这种情况随着工业的迅速发展而日益显著和严重，以至在五十年代和六十年代酿成震惊世界的严重公害病事件，如发生在日本的水俣病(长期食含汞量高的鱼引起的甲基汞中毒)和痛痛病(长期食含镉量高的米而引起的慢性镉中毒)。

环境污染与人群健康的关系，在世界范围，曾开展过广泛的研究，而这种研究一开始几乎都是流行病学调查研究。流行病学研究方法在这个领域中得到充分的运用和发展，逐渐形成具有自身特点的环境流行病学方法。由于对公害病的深入研究，在七十年代出现了一批环境流行病学的代表性文献。以后有人提出了“污染物的生物反应谱”概念，进一步概括了环境污染与人群健康状况之间关系的一般规律。

# 环境流行病学的研究范围与内容 

1. 调查并描述污染物(健康危害物)在区域环境各要素(空气、土壤、水体、生物)中的分布、负荷水平、时空波动、理化形态、转化规律、人群平均暴露水平和暴露条件(环境病因条件)等。
2. 调查并描述区域环境中暴露人群的健康状况构成 (生物反应谱)、地区、人群分布(按年龄、性别、职业、生活条件等特征分组)。
3. 研究环境污染物负荷与人群健康影响的对应关系即暴露一效应关系，确立剂量反应曲线。以此为基础，研究污染物的阈限负荷，制订环境质量标准，进而确定污染物的环境生物学容量。
4. 对原因未明的环境性疾病或人群健康异常进行流行病学的调查与分析，提出环境病因学线索，查明疾病与健康损害的直接原因。⑤研究环境健康影响的各因素联系以及诸环境因素相互作用及其对健康的影响。

# 环境流行病学的研究方法 

环境流行病学在研究特定环境因素对人群健康的影响时，必须遵循环境流行病学研究的一些重要的基本原则：

1. 大样本： 由于环境健康危害物在环境中的负荷通常较小，对人群的作用较弱，其健康效应往往仅在较易感的个体群中首先显现，并且只有较低的出现率。此外，社会条件、职业因素等皆可影响某种效应的出现率。因此应限于大数量的人群样本的研究，以便暴露出健康效应，并排除其它因素对出现率的影响。只有当已确知对某特定环境因素的易感人群存在时 (例如儿童对空气污染的作用易感)，才采用较小样本的特定人群来进行研究。
2. 有效性： 环境流行病学最本质的目的是确立暴露一效应因果关系。但是由于环境的多因素与复合性，要分离出单一因素加以研究，事实上不可能，这就必须考虑流行病学研究设计的有效性问题。为此，在选择人群的研究样本时，常选取对环境因素的有害作用最为敏感的那一部分人进行研究。为了提高研究的有效性，从高暴露人群入手，常能直接而迅速揭示出暴露—效应因果关系。如果能有计划地设置几个暴露梯度，观察该暴露梯度下人群的反应，则使研究工作更具有效性。
3. 对比性： 流行病学研究要揭示暴露人群与非暴露人群之间在健康效应方面的差异。要求调查研究设计应注意对比法。严格地选择非暴露人群作为对照组至关重要。不应在同一区域环境内选择对照点。在同一暴露人群中挑选所谓病例对照同样也是不科学的。
4. 多因素： 环境因素的健康效应受环境多种因素的影响。在研究某一已知因素的健康效应时，力求排除其它因素的干扰。在研究未知原因的健康异常或疾病时，力求探明主导因素以及辅助因素的影响。在研究设计中对关联因素应加以周密的考虑。
5. 分组原则： 暴露一效应关系常隐含在某一特定的环境负荷与相关人群的组合之中，例如某一年龄组，某一特定集团对于环境因素某种负荷呈现明显的暴露一效应关系。为了揭露出这种关联，必需设立若干暴露一效应梯度分组，进行统计分析。

一般流行病学研究方法在现代环境流行病学的实践中尚显得不够用。新投入环境中的化学物质，当其对人类健康的危害还未被认识以前，或者它的健康效应仅表现为个别现象，尚未构成适宜于统计分析的某种“率”(例如致畸胎事件)，用现有的流行病学方法就很难揭示其实际危害，因为①不易识别由化学物质引起的特殊病症或健康异常; ②其出现率极低难以收集一定数量的和相应的环境暴露资料。因此，流行病学研究方法尚待人们进一步探索和创新。








