project:
  type: website
  output-dir: docs
  preview:
    port: 4200
  resources: 
    - "Papers/*.pdf"

website:
  title: '环境暴露的人群健康效应的研究、写作与发表'
  page-footer:
    left: "Copyright 2023, 蔡苗"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "第一天"
        contents:
          - 0.intro.qmd
          - 1.exposure.qmd
          
      - section: "第二天"
        contents:
          - 2.ts.qmd
          - 3.cco.qmd
      - section: "第三天"
        contents:
          - 4.cross-sec.qmd
          - 5.cohort.qmd
      - section: "第四天"
        contents:
          - 6.writing.qmd
          - 7.journal.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    toc-title: '内容'
    smooth-scroll: true
    code-copy: true
    code-line-numbers: true
    code-block-bg: '#f0f0f0'
    code-block-border-left: "#31BAE9"

editor: source
page-navigation: true
execute:
  freeze: auto

